export { default as Login } from './Login'
export { default as AddActivity } from './AddActivity'
export { default as Camera } from './Camera'
export { default as MapComp } from './MapComp'
export { default as Dashboard } from './Dashboard'
