export { default as ProgressChart } from './ProgressChart'
export { default as ActivityChart } from './ActivityChart'
export { default as Login } from './Login'
export { default as AddActivity } from './AddActivity'
export { default as Camera } from './Camera'
export { default as MapComp } from './MapComp'
export { default as Dashboard } from './Dashboard'
export { default as Activity } from './Activity'
export { default as LoadingScreen } from './LoadingScreen'
export { default as ActivityCard } from './ActivityCard'
// export { default as UserActivities } from './UserActivities'
export { default as Leaderboard } from './Leaderboard'
export { default as Friends } from './Friends'
export { default as SearchUsers } from './search-users'
export { default as AddAd } from './AddAd'
